[project]
name = "websurfer-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "beautifulsoup4>=4.13.4",
    "mcp>=1.10.1",
    "trafilatura>=2.0.0",
    "validators>=0.35.0",
]
